version: '3.8'

services:
  mariadb: 
    build: .
    container_name: mariadb-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Claro2025*
      MYSQL_DATABASE: midb
      MYSQL_USER: mayra.soto
      MYSQL_PASSWORD: Claro2025*
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 tu_proyecto.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mariadb_data: